[build]
builder = "NIXPACKS"
buildCommand = "npm install --production=false"

[deploy]
startCommand = "node server-v21_1.js"
healthcheckPath = "/api/health/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
