[[services]]
name = "Inventory Backend"
rootDirectory = "inventory-enterprise/backend"
source = "inventory-enterprise/backend"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "node server-v21_1.js"
healthcheckPath = "/api/health/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
