[build]
builder = "NIXPACKS"
buildCommand = "npm install --production=false"

[deploy]
startCommand = "npm run start:postgres"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
